export const SET_CITY_ID='SET_CITY_ID';
export const FETCH_CITIES='FETCH_CITIES';
export const FETCH_CITIES_ERROR='FETCH_CITIES_ERROR';
export const SET_CITY_DETAILS='SET_CITY_DETAILS';
export const UPDATE_INPUT_VALUE='UPDATE_INPUT_VALUE';
export const SET_WEEKLY_WEATHER='SET_WEEKLY_WEATHER';
export const UPDATE_FAV_DATA='UPDATE_FAV_DATA';


